name: 'Datadog Lambda Deployer Action'
description: 'deploy a lambda function to launch performance test'
inputs:
  runtime_id:
    description: 'runtime'
    required: true
  layer_name:
    description: 'layer name'
    required: true
  layer_path:
    description: 'path to the zip file to be uploaded as a layer'
    required: true
  role:
    description: 'IAM role to use'
    required: true
  pr_number:
    description: 'PR number'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.runtime_id }}
    - ${{ inputs.layer_name }}
    - ${{ inputs.layer_path }}
    - ${{ inputs.role }}
    - ${{ inputs.pr_number }}