name: 'Datadog Lambda Deployer Action'
description: 'deploy a lambda function to launch performance test'
inputs:
  runtime_id:
    description: 'runtime'
    required: true
  layer_path:
    description: 'path to the zip file to be uploaded as a layer'
    required: true
  layer_name:
    description: 'layer name'
    required: true
  run_test:
    description: 'tells whether or not we should deploy a function and run a test'
    required: true
  role:
    description: 'IAM role to use'
    required: false
  extension_arn:
    description: 'Arn of the Datadog extension'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.runtime_id }}
    - ${{ inputs.layer_name }}
    - ${{ inputs.layer_path }}
    - ${{ inputs.run_test }}
    - ${{ inputs.role }}
    - ${{ inputs.extension_arn }}